# Generated by Django 4.0.3 on 2022-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_comments_userprofile_userpost_fundraiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
