# Generated by Django 4.0.3 on 2022-03-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(default=' ', upload_to='media/dynamic/img/user_image')),
                ('name', models.CharField(default=' ', max_length=40)),
                ('description', models.TextField()),
                ('location', models.CharField(default=' ', max_length=150)),
                ('tags', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
