# Generated by Django 4.0.3 on 2022-03-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tags',
            new_name='intrests',
        ),
    ]
