# Generated by Django 4.0.3 on 2022-03-26 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_tags_userprofile_intrests'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=' ', upload_to='media/dynamic/img/user_image')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(1)])),
                ('amount_received', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.fundraiser'),
        ),
    ]
