# Generated by Django 4.0.3 on 2022-03-26 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_fundraiser_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
