# Generated by Django 4.0.3 on 2022-03-26 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_fundraiser_amount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='amount_received',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
