# Generated by Django 4.0.3 on 2022-03-26 10:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_fundraiser_amount_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='date_joined',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(default=' ', upload_to='media/dynamic/img/user_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.CreateModel(
            name='Userpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=' ', upload_to='media/dynamic/img/user_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='normalpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.userpost'),
        ),
    ]
