# Generated by Django 4.0.3 on 2022-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_comments_rename_date_joined_fundraiser_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fundraiser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='normalpost',
        ),
    ]
