# Generated by Django 4.0.3 on 2022-03-26 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_groupdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdata',
            name='image',
            field=models.ImageField(default=' ', upload_to='dynamic/img/user_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
